# Generated by Django 2.1.5 on 2019-04-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='prortfolio_site',
            new_name='portfolio_site',
        ),
    ]
